manifest:

  projects:
    # --- CHANGE IS HERE ---
    # Instead of the full 'zephyr' repo, we're pulling 'zephyr-testing'.
    - name: ui-subsys
      path: ui-subsys-path
      url: https://github.com/khnmuhaimin/EEE4113F-Group-41-UI-Subsystem-2025
      revision: main

  # This section remains the same, defining your application.
  self:
    path: apps
